name: smart_socket_app_
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # Dart SDK sürümü

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3  # Bildirimler için eklenen paket
  permission_handler: ^11.3.1
  http: ^1.2.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # En son sürüme güncellendix"

flutter:
  uses-material-design: true

  assets:
    - assets/plug_image.png